version: "3.8"

services:
  jupyter-hub:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: jupyter-lab-${PROJECT_NAME}

    volumes:
      - type: bind
        source: ./config_files/
        target: /home/jupyter/.jupyter/
      - type: bind
        source: ./../
        target: /home/jupyter/project
      - type: bind
        source: ./viritual_env
        target: /home/jupyter/.local/share/jupyter/kernels/viritual_env

    ports:
      - "8888:8888"

